// src/core/ui/views/listing/listing.dummy.ts

import type { Listing } from "./listing.types";

export const dummyListings: Listing[] = [
    {
        id: "111",
        type: "service",
        name: "Ustadz Ahmad",
        price: 15000000,
        category: "Elektronik",
        location: "Bekasi",
        image: "https://placehold.co/300x200",
        rating: 4.9,
        sold: 120,
        isPromo: true,
        priceLabel: "Rp 50.000 / sesi",
    },
    {
        id: "1",
        type: "product",
        name: "Laptop Premium X",
        price: 15000000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 120,
        isPromo: true,
    },
    {
        id: "2",
        type: "product",
        name: "Kursi Ergonomis",
        price: 2500000,
        category: "Furniture",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 80,
    },
    {
        id: "3",
        type: "product",
        name: "Sepatu Running",
        price: 1200000,
        category: "Fashion",
        location: "Surabaya",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 200,
        isNew: true,
    },

    {
        id: "4",
        type: "product",
        name: "Smartphone Ultra 12GB",
        price: 8500000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 340,
    },
    {
        id: "5",
        type: "product",
        name: "Meja Kerja Minimalis",
        price: 1800000,
        category: "Furniture",
        location: "Depok",
        image: "https://placehold.co/300x200",
        rating: 4.4,
        sold: 95,
    },
    {
        id: "6",
        type: "product",
        name: "Jaket Hoodie Casual",
        price: 350000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 210,
        isNew: true,
    },

    {
        id: "7",
        type: "product",
        name: "Headphone Noise Cancelling",
        price: 2200000,
        category: "Elektronik",
        location: "Bekasi",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 175,
    },
    {
        id: "8",
        type: "product",
        name: "Lemari Pakaian 3 Pintu",
        price: 3200000,
        category: "Furniture",
        location: "Bogor",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 60,
    },
    {
        id: "9",
        type: "product",
        name: "Tas Ransel Travel",
        price: 450000,
        category: "Fashion",
        location: "Yogyakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 130,
    },

    {
        id: "10",
        type: "product",
        name: "Smartwatch Series 5",
        price: 2700000,
        category: "Elektronik",
        location: "Surabaya",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 155,
    },
    {
        id: "11",
        type: "product",
        name: "Sofa L Minimalis",
        price: 7500000,
        category: "Furniture",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 45,
    },
    {
        id: "12",
        type: "product",
        name: "Sneakers Street Style",
        price: 900000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 300,
        isPromo: true,
    },

    {
        id: "13",
        type: "product",
        name: "Monitor 27 Inch 4K",
        price: 5200000,
        category: "Elektronik",
        location: "Tangerang",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 110,
    },
    {
        id: "14",
        type: "product",
        name: "Rak Buku Kayu Solid",
        price: 2100000,
        category: "Furniture",
        location: "Semarang",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 70,
    },
    {
        id: "15",
        type: "product",
        name: "Kaos Polos Premium",
        price: 120000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.4,
        sold: 500,
    },

    {
        id: "16",
        type: "product",
        name: "Keyboard Mechanical RGB",
        price: 1500000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 190,
    },
    {
        id: "17",
        type: "product",
        name: "Tempat Tidur King Size",
        price: 6800000,
        category: "Furniture",
        location: "Surabaya",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 40,
    },
    {
        id: "18",
        type: "product",
        name: "Celana Jeans Slim Fit",
        price: 400000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 260,
    },

    {
        id: "19",
        type: "product",
        name: "Tablet Android 10 Inch",
        price: 3200000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 140,
    },
    {
        id: "20",
        type: "product",
        name: "Kursi Gaming RGB",
        price: 2900000,
        category: "Furniture",
        location: "Bekasi",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 120,
    },
    {
        id: "21",
        type: "product",
        name: "Topi Baseball Casual",
        price: 150000,
        category: "Fashion",
        location: "Depok",
        image: "https://placehold.co/300x200",
        rating: 4.3,
        sold: 310,
    },

    {
        id: "22",
        type: "product",
        name: "Kamera Mirrorless Pro",
        price: 12500000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.9,
        sold: 65,
    },
    {
        id: "23",
        type: "product",
        name: "Meja TV Modern",
        price: 2400000,
        category: "Furniture",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 75,
    },
    {
        id: "24",
        type: "product",
        name: "Sandal Casual Pria",
        price: 180000,
        category: "Fashion",
        location: "Surabaya",
        image: "https://placehold.co/300x200",
        rating: 4.4,
        sold: 220,
    },

    {
        id: "25",
        type: "product",
        name: "Drone Kamera 4K",
        price: 7800000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 90,
        isPromo: true,
    },
    {
        id: "26",
        type: "product",
        name: "Kabinet Dapur Minimalis",
        price: 4500000,
        category: "Furniture",
        location: "Bogor",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 55,
    },
    {
        id: "27",
        type: "product",
        name: "Jas Formal Pria",
        price: 950000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 180,
    },

    {
        id: "28",
        type: "product",
        name: "Speaker Bluetooth Bass Boost",
        price: 650000,
        category: "Elektronik",
        location: "Yogyakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 210,
    },
    {
        id: "29",
        type: "product",
        name: "Meja Belajar Anak",
        price: 1300000,
        category: "Furniture",
        location: "Semarang",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 95,
    },
    {
        id: "30",
        type: "product",
        name: "Dress Wanita Elegan",
        price: 550000,
        category: "Fashion",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 260,
    },

    {
        id: "31",
        type: "product",
        name: "Router WiFi 6",
        price: 1200000,
        category: "Elektronik",
        location: "Tangerang",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 130,
    },
    {
        id: "32",
        type: "product",
        name: "Kursi Kantor Premium",
        price: 2700000,
        category: "Furniture",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 85,
    },
    {
        id: "33",
        type: "product",
        name: "Kacamata Hitam UV Protection",
        price: 300000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.4,
        sold: 290,
    },

    {
        id: "34",
        type: "product",
        name: "SSD 1TB NVMe",
        price: 1800000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 170,
    },
    {
        id: "35",
        type: "product",
        name: "Lemari Sepatu Minimalis",
        price: 950000,
        category: "Furniture",
        location: "Depok",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 120,
    },
    {
        id: "36",
        type: "product",
        name: "Kaos Olahraga Dry Fit",
        price: 180000,
        category: "Fashion",
        location: "Surabaya",
        image: "https://placehold.co/300x200",
        rating: 4.3,
        sold: 340,
    },

    {
        id: "37",
        type: "product",
        name: "Printer All-in-One",
        price: 2100000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 110,
    },
    {
        id: "38",
        type: "product",
        name: "Meja Makan 6 Kursi",
        price: 7200000,
        category: "Furniture",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 50,
    },
    {
        id: "39",
        type: "product",
        name: "Tas Wanita Elegan",
        price: 650000,
        category: "Fashion",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 230,
    },

    {
        id: "40",
        type: "product",
        name: "Power Bank 20000mAh",
        price: 350000,
        category: "Elektronik",
        location: "Bekasi",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 410,
    },
    {
        id: "41",
        type: "product",
        name: "Rak Dinding Minimalis",
        price: 400000,
        category: "Furniture",
        location: "Bogor",
        image: "https://placehold.co/300x200",
        rating: 4.4,
        sold: 150,
    },
    {
        id: "42",
        type: "product",
        name: "Sepatu Formal Kulit",
        price: 1100000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 200,
    },

    {
        id: "43",
        type: "product",
        name: "Mouse Wireless Gaming",
        price: 550000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 260,
    },
    {
        id: "44",
        type: "product",
        name: "Sofa Bed Multifungsi",
        price: 4800000,
        category: "Furniture",
        location: "Surabaya",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 70,
    },
    {
        id: "45",
        type: "product",
        name: "Celana Chino Pria",
        price: 350000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 300,
    },

    {
        id: "46",
        type: "product",
        name: "Webcam Full HD",
        price: 750000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 180,
    },
    {
        id: "47",
        type: "product",
        name: "Meja Rias Minimalis",
        price: 2100000,
        category: "Furniture",
        location: "Yogyakarta",
        image: "https://placehold.co/300x200",
        rating: 4.5,
        sold: 90,
    },
    {
        id: "48",
        type: "product",
        name: "Outer Wanita Korean Style",
        price: 420000,
        category: "Fashion",
        location: "Bandung",
        image: "https://placehold.co/300x200",
        rating: 4.7,
        sold: 270,
    },

    {
        id: "49",
        type: "product",
        name: "TV Smart 50 Inch",
        price: 6800000,
        category: "Elektronik",
        location: "Jakarta",
        image: "https://placehold.co/300x200",
        rating: 4.8,
        sold: 140,
    },
    {
        id: "50",
        type: "product",
        name: "Kursi Santai Rotan",
        price: 1900000,
        category: "Furniture",
        location: "Bali",
        image: "https://placehold.co/300x200",
        rating: 4.6,
        sold: 60,
    },
];
