/* eslint-disable @typescript-eslint/no-explicit-any */
// src/core/ui/icons/icon.registry.ts

import {
    ArchiveBoxIcon,
    BookmarkIcon,
    CalendarIcon,
    CheckCircleIcon,
    CheckIcon,
    DocumentCurrencyDollarIcon,
    DocumentIcon,
    EyeSlashIcon,
    KeyIcon,
    LifebuoyIcon,
    LockClosedIcon,
    PercentBadgeIcon,
    PlayCircleIcon,
    PlusCircleIcon,
    ReceiptPercentIcon,
    TagIcon,
    UserIcon,
    WifiIcon,
} from "@heroicons/react/20/solid";
import { TvIcon } from "@heroicons/react/20/solid";
import { UsersIcon } from "@heroicons/react/20/solid";
import { FireIcon } from "@heroicons/react/20/solid";
import { CheckBadgeIcon } from "@heroicons/react/20/solid";
import { ClockIcon, ReceiptRefundIcon } from "@heroicons/react/20/solid";
import {
    BellAlertIcon,
    BookOpenIcon,
    ChartBarSquareIcon,
    CurrencyDollarIcon,
    InboxArrowDownIcon,
    MapPinIcon,
    QuestionMarkCircleIcon,
    ShieldCheckIcon,
    UserGroupIcon,
    PencilSquareIcon,
    XCircleIcon,
    EyeIcon,
    PlusIcon,
    HomeIcon,
    // UserIcon,
    UserCircleIcon,
    ChartBarIcon,
    CubeIcon,
    ShoppingCartIcon,
    ArrowRightStartOnRectangleIcon,
    ChevronDownIcon,
    Cog6ToothIcon,
    BriefcaseIcon,
    MagnifyingGlassCircleIcon,
    CalendarDateRangeIcon,
    CreditCardIcon,
    WalletIcon,
    PauseCircleIcon,
} from "@heroicons/react/20/solid";
import { ShoppingBagIcon } from "@heroicons/react/24/outline";
import { BellIcon } from "@heroicons/react/24/outline";

export const iconRegistry: Record<string, any> = {
    // Action Icons
    edit: PencilSquareIcon,
    delete: XCircleIcon,
    view: EyeIcon,
    create: PlusIcon,

    // Navigation Icons
    home: HomeIcon,
    "user-check": UserCircleIcon,
    plus: PlusIcon,
    "chart-line": ChartBarIcon,
    "shopping-cart": ShoppingCartIcon,
    box: CubeIcon,

    // System Icons
    "log-out": ArrowRightStartOnRectangleIcon,
    "chevron-down": ChevronDownIcon,
    cog: Cog6ToothIcon,

    briefcase: BriefcaseIcon,
    search: MagnifyingGlassCircleIcon,
    calendar: CalendarDateRangeIcon,
    "credit-card": CreditCardIcon,
    eye: EyeIcon,
    "eye-off": EyeSlashIcon,
    wallet: WalletIcon,
    booking: BookOpenIcon,
    help: QuestionMarkCircleIcon,
    notification: BellAlertIcon,
    inbox: InboxArrowDownIcon,
    "map-pin": MapPinIcon,
    "dollar-sign": CurrencyDollarIcon,
    users: UserGroupIcon,
    shield: ShieldCheckIcon,
    "bar-chart": ChartBarSquareIcon,
    "pause-circle": PauseCircleIcon,
    "rotate-ccw": ReceiptRefundIcon,
    clock: ClockIcon,
    "file-plus": PlusCircleIcon,
    "check-circle": CheckCircleIcon,
    receipt: ReceiptPercentIcon,
    check: CheckIcon,
    "calendar-plus": CalendarIcon,
    tool: TvIcon,
    "check-square": CheckBadgeIcon,
    package: FireIcon,
    "file-text": DocumentIcon,
    lock: KeyIcon,
    percent: PercentBadgeIcon,
    archive: ArchiveBoxIcon,
    target: TagIcon,
    user: UserIcon,
    "play-circle": PlayCircleIcon,
    book: BookmarkIcon,
    wifi: WifiIcon,
    "life-buoy": LifebuoyIcon,
    profile: UsersIcon,
    transaction: DocumentCurrencyDollarIcon,
    login: LockClosedIcon,
    bell: BellIcon,
    order: ShoppingBagIcon,
};
